"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#071A2F)\
$username\
[](bg:#0F2A44 fg:#071A2F)\
$directory\
[](fg:#0F2A44 bg:#164E63)\
$git_branch\
$git_status\
[](fg:#164E63 bg:#0EA5E9)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#0EA5E9 bg:#38BDF8)\
$docker_context\
[](fg:#38BDF8 bg:#0F2A44)\
$time\
[ ](fg:#0F2A44)\
"""

# USER
[username]
show_always = true
style_user = "bg:#071A2F fg:#F8FAFC bold"
style_root = "bg:#071A2F fg:#F8FAFC bold"
format = "[ fermin ]($style)"

# DIRECTORY
[directory]
style = "bg:#0F2A44 fg:#F8FAFC bold"
format = "[ $path ]($style)"
truncation_length = 3

# GIT
[git_branch]
symbol = ""
style = "bg:#164E63 fg:#F8FAFC bold"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#164E63 fg:#F8FAFC"
format = "[$all_status$ahead_behind ]($style)"

# LANGUAGES
[c]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[cpp]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[elixir]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[elm]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[golang]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[gradle]
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[haskell]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[java]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[julia]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[nodejs]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[nim]
symbol = "󰆥 "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[rust]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

[scala]
symbol = " "
style = "bg:#0EA5E9 fg:#020617"
format = "[ $symbol $version ]($style)"

# DOCKER
[docker_context]
symbol = " "
style = "bg:#38BDF8 fg:#020617"
format = "[ $symbol $context ]($style)"

# TIME
[time]
disabled = false
time_format = "%R"
style = "bg:#0F2A44 fg:#F8FAFC bold"
format = "[ $time ]($style)"
